### ISSUE TITLE
[Gateway] Low latency support

### ISSUE THREAD

**Issue by johannmika** [5G-MAG/Documentation-and-Architecture#12]
The reference client functionality should be extended to low latency support to enable low latency (LL) for LTE-based 5G terrestrial broadcast and to provide a comparable latency with LL OTT streams provided via CDN.

**Is your feature request related to a problem? Please describe.**
- The current gateway is not  supporting low latency streams via 5G broadcast. Thus, the necessary changes on the gateway process, i.e. mainly the 

**Describe the solution you'd like**

- Nginx support for LL-DASH and LL-HLS should be provided.
- End-2-end test with live setup (Origin - 5G BC core (R&S BSCC) - Transmitter - Receiver with gateway LL extension - open source LL player (e.g. DASH.js HLS.hs?) should be performed.

**Which parts of the reference client are affected**
- Gateway

**Who takes care about the develepment**
- Development will be done by ORS development resources.

**Comment by dsilhavy** [comment]
Created an issue for this in the MW repo: https://github.com/5G-MAG/rt-mbms-mw/issues/2
