### ISSUE TITLE
[Gateway] Seamless streaming 'basic'

### ISSUE THREAD

**Issue by johannmika** [5G-MAG/Documentation-and-Architecture#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dsilhavy** [comment]
Created a new issue for this here: https://github.com/5G-MAG/rt-mbms-mw/issues/3. @johannmika Can you please edit the description in the new issue. I suppose this is about switching between broadcast and unicast mode?
