### ISSUE TITLE
[Receiver] Add Rel16 features

### ISSUE THREAD

**Issue by johannmika** [5G-MAG/Documentation-and-Architecture#14]
**Is your feature request related to a problem? Please describe.**
The receiver functionality should be extended to meet community requests for Rel16 features and to support features already available on the transmitter side.

**Describe the solution you'd like**
- SCS 0.37 kHz
- PBCH repetition
- Aggregation level 16
- CFI-indicator in MIB-MBMS
- CP 200 us
- CP 300 us

**Which parts of the reference client are affected**
- Receiver

**Who takes care about the develepment**
- Development will be done by ORS development resources.

**Comment by dsilhavy** [comment]
I created an issue for that in the MBMS-Modem project: https://github.com/5G-MAG/rt-mbms-modem/issues/3 

Closing this one
