### ISSUE TITLE
Webinterface Wiki Page instructions incorrect

### ISSUE THREAD

**Issue by ben-EDT** [5G-MAG/Documentation-and-Architecture#28]
**Describe the bug**
Instructions for Webinterface in the Wiki do not reflect the updates to the rt-wui for the naming changes.

**To Reproduce**
1. Following the steps on the wiki will not work if you have followed the rt-wui README instructions

**Expected behavior**
Following the instructions on the wiki page should mirror those in the rt-wui README file

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - N/A

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
I re-wrote the rt-wui instructions in the README in line with the naming changes agreed in RT WG developers calls

I have attached a modified version of the relevant wiki page which will solve this Issue, it just needs to be renamed and replace the file Webinterface.md
[rt-wui.md](https://github.com/5G-MAG/Documentation-and-Architecture/files/7441482/rt-wui.md)

**Comment by dsilhavy** [comment]
Merged
