### ISSUE TITLE
Failed to start rt-wui as daemon

### ISSUE THREAD

**Issue by FMPandolfi** [5G-MAG/Documentation-and-Architecture#33]
Hi,

Please specify in the Webinterface Installation instructions to change also the daemon user in rt-wui.service as it defaults to ofr (which is normally not available and it gives error).

It would be nice to have it set by default to `fivegmag-rt` since this is already added during the modem installation.

Thanks for the great work!

**Comment by dsilhavy** [comment]
Addressed in https://github.com/5G-MAG/rt-wui/pull/10
